#!/bin/sh

mkdir -p opk
cp ./desmume.elf opk/desmume.elf
cp ./cursor.bmp opk/cursor.bmp
cp ./icon.png opk/icon.png
cp ./COPYING opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=LameDS
Comment=Horrible NDS emulator
Exec=desmume.elf %f
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
SelectorFilter=nds
X-OD-NeedsDownscaling=true' > opk/default."$1".desktop

mksquashfs ./opk lameds_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
